# Generated by Django 4.0.4 on 2022-05-10 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_name',
        ),
    ]
